import { DemoMetadata } from "../../../types"; // Adjust the import path to match your structure

export const quantumNebulaDocumentation: DemoMetadata = {
    title: "Quantum Nebula",
    concepts: [
        "Black Hole Gravity",
        "Polar Jets",
        "Additive Blending",
        "Velocity Stretching",
        "Holographic Post-Processing"
    ],
    sections: [
        {
            heading: "Overview",
            isOpen: true,
            text: "This demo renders a massive, chaotic galaxy of 200,000 particles orbiting a central supermassive anomaly. It demonstrates how to combine WebGPU's <strong>Additive Blending</strong> pipeline states with complex compute shader physics to simulate a black hole's gravity well, complete with relativistic polar jets that violently eject matter escaping the event horizon."
        },
        {
            heading: "Compute Physics: Gravity & Polar Jets",
            text: "The compute shader orchestrates four distinct forces to create the galactic shape. First, an orbit force is generated by taking the cross product of the particle's direction and the world's up-vector. Second, a gravity well pulls particles inward using a modified inverse-distance formula. Third, if a particle crosses the 'event horizon' (distance < 20 units), gravity is suddenly weakened and a massive <strong>Jet Force</strong> is applied along the $Y$-axis, launching the particle out of the nearest pole.",
            code: `// 1. GALAXY SWIRL (Perpendicular force to create orbit)
let up = vec3<f32>(0.0, 1.0, 0.0);
let orbitDir = cross(up, dir);
let orbitForce = orbitDir * 150.0;

// 2. BLACK HOLE GRAVITY (Pulls inwards)
var gravityForce = -dir * (8000.0 / (dist + 10.0));

// 3. EVENT HORIZON REPULSION (Shoots out of poles)
var jetForce = vec3<f32>(0.0);
if (dist < 20.0) {
    let poleDir = sign(pos.y + 0.001); // Up or down
    jetForce = vec3<f32>(0.0, poleDir * 300.0, 0.0);
    gravityForce *= 0.1; // Weakened gravity at the core
}`
        },
        {
            heading: "Rendering Technique: Additive Blending",
            text: "Instead of standard opaque or alpha-blended rendering, this pipeline explicitly modifies the WebGPU depth and blend states. Depth writing is disabled (<code>depthWriteEnabled: false</code>), and the blend operation is set to <code>add</code>. Because overlapping fragments sum their color values together algebraically, dense clusters of particles natively create blindingly bright, glowing cores without needing complex lighting models.",
            code: `// WebGPU Pipeline Descriptor for Additive Blending
blend: {
    color: { srcFactor: 'src-alpha', dstFactor: 'one', operation: 'add' },
    alpha: { srcFactor: 'one', dstFactor: 'one', operation: 'add' }
},
depthWriteEnabled: false,
depthCompare: 'less'`
        },
        {
            heading: "Geometry Stretching",
            text: "To emphasize the extreme speeds of the particles (especially those caught in the polar jets), the vertex shader dynamically stretches the base cube geometry along its velocity vector. By constructing a custom rotation matrix and scaling the local $Z$-axis relative to the particle's speed, cubes are deformed into long, sleek light streaks.",
            code: `// Stretch cubes along their velocity vector to look like light streaks
let forward = normalize(vel + vec3<f32>(0.001, 0.0, 0.0));
...
let rotMat = mat3x3<f32>(right, realUp, forward);

let speed = length(vel);
// Base size 0.2, stretches up to 4.0 units based on speed
let scaleVec = vec3<f32>(0.2, 0.2, 0.1 + (speed * 0.02)); 
let orientedPos = rotMat * (localPos * scaleVec);`
        },
        {
            heading: "Post-Processing: Hologram & ACES",
            text: "Because additive blending pushes pixel values extremely high, the scene requires tonemapping to preserve color detail. The fragment shader applies the <strong>ACES Filmic Tonemap</strong> to smoothly roll off the harsh whites into saturated colors. To finalize the aesthetic, it introduces radial <strong>Chromatic Aberration</strong>—shifting the red and blue channels outward based on their distance from the center—and overlays moving holographic scanlines."
        }
    ]
};