export const hyperchaosComputeShader = `
    struct IndirectDrawArgs { indexCount: u32, instanceCount: atomic<u32>, firstIndex: u32, baseVertex: u32, firstInstance: u32 };
    struct Camera { viewProj: mat4x4<f32>, eye: vec3<f32>, simTime: f32 };
    
    @group(0) @binding(0) var<uniform> camera: Camera; 
    @group(0) @binding(1) var<storage, read_write> physicsState: array<f32>;
    @group(0) @binding(2) var<storage, read_write> renderData: array<f32>;
    @group(0) @binding(3) var<storage, read_write> drawArgs: IndirectDrawArgs;

   @compute @workgroup_size(64)
    fn cs_main(@builtin(global_invocation_id) global_id: vec3<u32>) {
        let idx = global_id.x;
        if (idx >= 200000u) { return; } 

        let time = camera.simTime;
        let base = idx * 16u;

        // Extract 4D position
        var pos4D = vec4<f32>(
            physicsState[base + 1u], 
            physicsState[base + 2u], 
            physicsState[base + 3u], 
            physicsState[base + 4u]
        );

        // 1. THE RÖSSLER HYPERCHAOS EQUATIONS (1979)
        // These constants dictate the folding behavior of the attractor in 4D space
        let a = 0.25;
        let b = 3.0;
        let c = 0.5;
        let d = 0.05;

        // Differential equations for 4D hyperchaos
        let dx = -pos4D.y - pos4D.z;
        let dy = pos4D.x + a * pos4D.y + pos4D.w;
        let dz = b + pos4D.x * pos4D.z;
        let dw = -c * pos4D.z + d * pos4D.w;

        // Integration (Euler method with small time step for stability)
        let dt = 0.004;
        var vel4D = vec4<f32>(dx, dy, dz, dw);
        pos4D += vel4D * dt;

        // Containment: If particles get blown out by chaos, reset them near the origin
        if (length(pos4D) > 200.0) {
            pos4D = vec4<f32>(0.1, 0.1, 0.1, 0.1);
        }

        // 2. STEREOGRAPHIC PROJECTION (4D to 3D)
        // We project from the "North Pole" of the 4-sphere down to 3D space.
        // As particles move through the 4th dimension (W), they scale and warp in 3D.
        let projectionPole = 40.0; 
        let projScale = projectionPole / (projectionPole - pos4D.w);
        let pos3D = pos4D.xyz * projScale;
        
        // Calculate 3D velocity for stretching the mesh later
        let lastPos3D = vec3<f32>(physicsState[base + 5u], physicsState[base + 6u], physicsState[base + 7u]);
        let vel3D = pos3D - lastPos3D;

        // 3. 4D COLOR MAPPING
        // Color is determined by where the particle currently sits in the unseen 4th dimension
        let wNormalized = clamp((pos4D.w + 20.0) / 40.0, 0.0, 1.0);
        
        let colorDeep = vec3<f32>(0.02, 0.1, 0.8);   // Deep ultraviolet
        let colorMid  = vec3<f32>(0.0, 0.9, 0.7);    // Bioluminescent teal
        let colorHigh = vec3<f32>(1.0, 0.9, 0.2);    // Blazing gold

        var finalColor = mix(colorDeep, colorMid, smoothstep(0.0, 0.5, wNormalized));
        finalColor = mix(finalColor, colorHigh, smoothstep(0.5, 1.0, wNormalized));

        // Add energy based on the speed of the chaos
        finalColor *= 1.0 + (length(vel4D) * 0.05);

        // 4. WRITE STATE BACK
        physicsState[base + 1u] = pos4D.x; physicsState[base + 2u] = pos4D.y; 
        physicsState[base + 3u] = pos4D.z; physicsState[base + 4u] = pos4D.w;
        
        // Store last 3D pos for velocity calculation next frame
        physicsState[base + 5u] = pos3D.x; physicsState[base + 6u] = pos3D.y; physicsState[base + 7u] = pos3D.z;

        // 5. WRITE RENDER DATA
        let writeIdx = atomicAdd(&drawArgs.instanceCount, 1u);
        let wBase = writeIdx * 16u;
        
        // Pass 3D position
        renderData[wBase + 1u] = pos3D.x; renderData[wBase + 2u] = pos3D.y; renderData[wBase + 3u] = pos3D.z;
        // Pass 3D velocity
        renderData[wBase + 4u] = vel3D.x; renderData[wBase + 5u] = vel3D.y; renderData[wBase + 6u] = vel3D.z;
        // Pass Color
        renderData[wBase + 11u] = finalColor.r; renderData[wBase + 12u] = finalColor.g; renderData[wBase + 13u] = finalColor.b;
    }
`;

export const hyperchaosRenderShader = `
    struct Camera { viewProj: mat4x4<f32> };
    @group(0) @binding(0) var<uniform> camera: Camera;
    @group(0) @binding(1) var<storage, read> ecs: array<f32>;

    struct VertexOut {
        @builtin(position) pos: vec4<f32>,
        @location(0) color: vec3<f32>,
    };

    @vertex
    fn vs_main(@location(0) localPos: vec3<f32>, @builtin(instance_index) iIdx: u32) -> VertexOut {
        let base = iIdx * 16u;
        let pos = vec3<f32>(ecs[base + 1u], ecs[base + 2u], ecs[base + 3u]);
        let vel = vec3<f32>(ecs[base + 4u], ecs[base + 5u], ecs[base + 6u]); 
        let baseColor = vec3<f32>(ecs[base + 11u], ecs[base + 12u], ecs[base + 13u]);

        // Orient the shards along the complex 3D paths generated by the 4D projection
        let forward = normalize(vel + vec3<f32>(0.0001, 0.0, 0.0));
        var right = cross(vec3<f32>(0.0, 1.0, 0.0), forward);
        if (length(right) < 0.001) { right = cross(vec3<f32>(1.0, 0.0, 0.0), forward); }
        right = normalize(right);
        let up = cross(forward, right);
        let rotMat = mat3x3<f32>(right, up, forward);
        
        let speed = clamp(length(vel), 0.0, 15.0);
        // Make them incredibly thin and stretched out to look like continuous ribbons/threads
        let scaleVec = vec3<f32>(0.05, 0.05, 0.5 + speed * 0.8);
        
        let worldPosition = rotMat * (localPos * scaleVec) + pos;
        let screenPos = camera.viewProj * vec4<f32>(worldPosition, 1.0);

        var out: VertexOut;
        out.pos = screenPos;
        out.color = baseColor; 
        return out;
    }

    @fragment
    fn fs_main(@location(0) color: vec3<f32>) -> @location(0) vec4<f32> {
        return vec4<f32>(color, 1.0); 
    }
`;